version: '3'
services:
  mongodb:
    image: mongo:4.2.0
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    ports:
      - 27017:27017
    volumes:
      - db-data:/data/db
      - mongo-config:/data/configdb
    #command: mongod --smallfiles --logpath=/dev/null # --quiet

volumes:
  db-data:
  mongo-config:
